config/routes.rb
Rails.application.routes.draw do
  resources :picture_frames
  get 'picture_frames/portrait'

  get 'password_resets/new'

  get 'password_resets/edit'

  get 'sessions/new'

  get 'uses/new'

 resources :pins



  resources :pins do
  	resources :pins
  	member do
  		put "like",    to: "pins#upvote"
  	end
  end

  root "pins#index"
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  get 'signup'  => 'uses#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  resources :uses

  resources :pins
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :microposts,          only: [:create, :destroy]


end

app/models/pin.rb
class Pin < ActiveRecord::Base

  acts_as_votable
	belongs_to :use

# This is where you set what imagemagick will resize your variants to
	has_attached_file :image, :styles => { :large => "960x960>", :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
  validates :image, :attachment_presence => true
  validates :image, dimensions: { width: 700, height: 500 }
after_create :get_the_aspect

  





def self.search(search)
query = "%#{search}%"
  if search
Pin.where("title like ? or description like ?", query, query,)

  else
Pin.all
  end
end

  def get_the_aspect()
          dimensions = Paperclip::Geometry.from_file(image.queued_for_write[:original].path)

      if
      dimensions.width / dimensions.height >= 0.8 && dimensions.width / dimensions.height <= 1.2

        self.update_column(:aspect, 3)

elsif
        dimensions.vertical?

        self.update_column(:aspect, 2)

      else
                 dimensions.horizontal?

        self.update_column(:aspect, 1)


      end
    end
  end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
		before_action :find_pin, only: [:show, :edit, :update, :destroy, :upvote, :downvote]



  
  def index
    @pins = Pin.paginate(page: params[:page], per_page: 6).order("created_at DESC")
	    respond_to do |format|
	    format.html
	    format.js # add this line for your js template

  if params[:search]
    @pins = Pin.search(params[:search]).order("created_at DESC").paginate(page: params[:page], per_page: 9)

  else
    @pins = Pin.paginate(page: params[:page], per_page: 9).order("created_at DESC")
    @microposts = current_use.microposts.build if logged_in?
  end
end
end







  def home
    @pins = Pin.where(:use_id => current_use.id).paginate(:page => params[:page])
    if signed_in?
      @micropost  = current_use.microposts.build
      @feed_items = current_use.feed.paginate(page: params[:page])
  end
end







  

	def show
		@pins = Pin.all
@picture_frames = PictureFrame.all
    @microposts = current_use.microposts.build if logged_in?
	end

	def new
		@pin = current_use.pins.build

	end




	def create
		@pin = current_use.pins.build(pin_params)
		if @pin.save
			redirect_to @pin, notice: "Art successfully created"
		else
			render 'new'
		end
	end

	

	def edit

	end

	def update
		if @pin.update(pin_params)
			redirect_to @pin, notice: "Successfully updated"
		else
			render 'edit'
		end
	end

	def destroy
		@pin.destroy
		redirect_to root_path
	end

	def upvote
		if logged_in?
		@pin.upvote_by current_use
		redirect_to :back
else
		
		redirect_to (login_path)
end
		
	end

private

def pin_params
		params.require(:pin).permit(:title, :description, :image, :aspect, :image_meta)
end
	

	def find_pin
		@pin = Pin.find(params[:id])
end

end

app/helpers/pins_helper.rb
module PinsHelper
	
end

app/views/pins/_form.html.haml
= simple_form_for @pin, html: { multipart: true } do |f|
	- if @pin.errors.any?
		#errors
	
			%ul
				- @pin.errors.full_messages.each do |msg|
					%li= msg

	.form-group
		= f.input :image, input_html: { class: 'form-control' }

	.form-group
		= f.input :title, input_html: { class: 'form-control' }

	.form-group
		= f.input :description, input_html: { class: 'form-control' }
		

	= f.button :submit, class: "btn btn-primary"


app/views/pins/edit.html.haml
#edit_page.col-md-8.col-md-offset-2
	.row
		.panel.panel-default
			.panel-heading
				%h1 Edit Art Feature
			.panel-body
				.current_image
					%strong.center Current Image
					= image_tag @pin.image.url(:medium)
				= render 'form'

app/views/pins/index.html.haml
#pins.transitions-enabled
	- @pins.each do |pin|
		.box.panel.panel-default.mymargin
			#my-posts
				.index_frame_container.cover
					= image_tag pin.image.url(:medium), :class => "style_image" + pin.aspect.to_s, :style => "top: #{@picture_frames = PictureFrame.where(aspect_frame: pin.aspect.to_s).limit(1).take!.top}" + '%; ' "left: #{@picture_frames = PictureFrame.where(aspect_frame: pin.aspect.to_s).limit(1).take!.left}" + '%;' "width: #{101 - @picture_frames = PictureFrame.where(aspect_frame: pin.aspect.to_s).limit(1).take!.left * 2}" + '%; ' "height: #{101 - @picture_frames = PictureFrame.where(aspect_frame: pin.aspect.to_s).limit(1).take!.top * 2}" + '%;'  
					= image_tag @picture_frames = PictureFrame.where(aspect_frame: pin.aspect.to_s).limit(1).take!.image.url(:original), :class => "style_image_frame" + pin.aspect.to_s


				%h2= link_to pin.title, pin
				%p.use
					Submitted by
					= pin.use.name
					= pin.image.aspect_ratio(:original)
.col-md-4.col-md-offset-4.center			
	#infinite-scrolling
		= will_paginate @pins



app/views/pins/new.html.haml
.col-md-8.col-md-offset-2
	.row
		.panel.panel-default
			.panel-heading
				%h1 Create New Art Feature
			.panel-body
				= render 'form'

app/views/pins/show.html.haml
#pin_show.row
	.col-md-8.col-md-offset-2
		.panel.panel-default
			.panel-heading.pin_image

				.index_frame_container
					= image_tag @pin.image.url(:large), :class => "style_image" + @pin.aspect.to_s, :style => "top: #{@picture_frames = PictureFrame.where(aspect_frame: @pin.aspect.to_s).limit(1).take!.top}" + '%; ' "left: #{@picture_frames = PictureFrame.where(aspect_frame: @pin.aspect.to_s).limit(1).take!.left}" + '%;' "width: #{101 - @picture_frames = PictureFrame.where(aspect_frame: @pin.aspect.to_s).limit(1).take!.left * 2}" + '%;' "height: #{101 - @picture_frames = PictureFrame.where(aspect_frame: @pin.aspect.to_s).limit(1).take!.top * 2}" + '%;'
					= image_tag @picture_frames = PictureFrame.where(aspect_frame: @pin.aspect.to_s).limit(1).take!.image.url(:original), :class => "style_image_frame" + @pin.aspect.to_s, id: 'frame-flipper'

			.panel-body
				%h1= @pin.title
				%p.description= @pin.description
			.panel-footer
				.row
					.col-md-6
						%p.user
							Submitted by
							= @pin.use.name
					.col-md-6
						.btn-group.pull-right
							= link_to like_pin_path(@pin), method: :put, class: "btn btn-default" do
								%span.glyphicon.glyphicon-heart
								= @pin.get_upvotes.size
							- if current_use?(@pin.use)
								= link_to "Edit", edit_pin_path, class: "btn btn-default"
								= link_to "Delete", pin_path, method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-default"


.panel-heading
	#pictureframes.transitions-enabled
		- @picture_frames = PictureFrame.all.where(aspect_frame: @pin.aspect.to_s).each do |picture_frame|
			.box.panel.panel-default.mymargin
				.index_frame_container
					= image_tag @pin.image.url(:large), :class => "style_image" + @pin.aspect.to_s, :style => "top: #{@picture_frames = PictureFrame.where(aspect_frame: @pin.aspect.to_s).limit(1).take!.top}" + '%; ' "left: #{@picture_frames = PictureFrame.where(aspect_frame: @pin.aspect.to_s).limit(1).take!.left}" + '%;' "width: #{101 - @picture_frames = PictureFrame.where(aspect_frame: @pin.aspect.to_s).limit(1).take!.left * 2}" + '%;' "height: #{101 - @picture_frames = PictureFrame.where(aspect_frame: @pin.aspect.to_s).limit(1).take!.top * 2}" + '%;'
					= image_tag picture_frame.image.url


- if logged_in?
	.row
	%aside.col-md-4
		%section.user_info
			= render 'shared/use_info'
		%section.micropost_form
			= render 'shared/micropost_form'



- else
	.center.jumbotron
	%h1 Welcome to ArtRising.ie
	%h2
	This is the home page for the
	%a{:href => "http://www.railstutorial.org/"} Ruby on Rails Tutorial
	sample application.
	= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary"  
%end 
.panel-heading                |
	.row
		.col-md-6
			%p.user
			Submitted by
			= @pin.use.name
.panel-heading                |
	.row
		.col-md-6
			%p.user
			Submitted by
			= @pin.use.name
.panel-heading                |
	.row
		.col-md-6
			%p.user
			Submitted by
			= @pin.use.name