config/routes.rb
Rails.application.routes.draw do
  resources :picture_frames
  get 'picture_frames/portrait'

  get 'password_resets/new'

  get 'password_resets/edit'

  get 'sessions/new'

  get 'uses/new'

 resources :pins



  resources :pins do
  	resources :pins
  	member do
  		put "like",    to: "pins#upvote"
  	end
  end

  root "pins#index"
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  get 'signup'  => 'uses#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  resources :uses

  resources :pins
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :microposts,          only: [:create, :destroy]


end

app/models/picture_frame.rb
class PictureFrame < ActiveRecord::Base
belongs_to :pins
	has_attached_file :image, :styles => { :large => "960x480>", :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
  validates :image, :attachment_presence => true
after_create :get_the_aspect_frame

end

  def get_the_aspect_frame()
          dimensions = Paperclip::Geometry.from_file(image.queued_for_write[:original].path)

      if
      (dimensions.width / dimensions.height >= 0.9) && (dimensions.width / dimensions.height <= 1.2)

        self.update_column(:aspect_frame, 3)

elsif
        dimensions.vertical?

        self.update_column(:aspect_frame, 2)

      else
                 dimensions.horizontal?

        self.update_column(:aspect_frame, 1)


      end
    end

app/controllers/picture_frames_controller.rb
class PictureFramesController < ApplicationController
  before_action :set_picture_frame, only: [:show, :edit, :update, :destroy]

  # GET /picture_frames
  # GET /picture_frames.json
  def index
    @picture_frames = PictureFrame.all
  end

  # GET /picture_frames/1
  # GET /picture_frames/1.json
  def show
      @picture_frames = PictureFrame.all
  end

    def portrait
       @picture_frames = PictureFrame.aspect
  end

  # GET /picture_frames/new
  def new
    @picture_frame = PictureFrame.new
  end

  # GET /picture_frames/1/edit
  def edit
  end

  # POST /picture_frames
  # POST /picture_frames.json
  def create
    @picture_frame = PictureFrame.new(picture_frame_params)

    respond_to do |format|
      if @picture_frame.save
        format.html { redirect_to @picture_frame, notice: 'Picture frame was successfully created.' }
        format.json { render :show, status: :created, location: @picture_frame }
      else
        format.html { render :new }
        format.json { render json: @picture_frame.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /picture_frames/1
  # PATCH/PUT /picture_frames/1.json
  def update
    respond_to do |format|
      if @picture_frame.update(picture_frame_params)
        format.html { redirect_to @picture_frame, notice: 'Picture frame was successfully updated.' }
        format.json { render :show, status: :ok, location: @picture_frame }
      else
        format.html { render :edit }
        format.json { render json: @picture_frame.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /picture_frames/1
  # DELETE /picture_frames/1.json
  def destroy
    @picture_frame.destroy
    respond_to do |format|
      format.html { redirect_to picture_frames_url, notice: 'Picture frame was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_picture_frame
      @picture_frame = PictureFrame.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def picture_frame_params
      params.require(:picture_frame).permit(:name, :image_url, :image, :id, :aspect_frame, :image_meta, :top, :left)
    end
end

app/helpers/picture_frames_helper.rb
module PictureFramesHelper
end

app/views/picture_frames/_form.html.haml
= simple_form_for @picture_frame, html: { multipart: true } do |f|
	- if @picture_frame.errors.any?
		#errors
	
			%ul
				- @picture_frame.errors.full_messages.each do |msg|
					%li= msg

	.form-group
		= f.input :image, input_html: { class: 'form-control' }

	.form-group
		= f.input :name, input_html: { class: 'form-control' }

	.form-group
	= f.input :top, input_html: { class: 'form-control' }

	.form-group
	= f.input :left, input_html: { class: 'form-control' }	

	= f.button :submit, class: "btn btn-primary"

app/views/picture_frames/edit.html.haml
#edit_page.col-md-8.col-md-offset-2
	.row
		.panel.panel-default
			.panel-heading
				%h1 Edit Art Feature
			.panel-body
				.current_image
					%strong.center Current Image
					= image_tag @picture_frame.image.url(:medium)
				= render 'form'

app/views/picture_frames/index.html.haml
#pins.transitions-enabled
  - @picture_frames.each do |picture_frame|   
    .box.panel.panel-default
      = link_to (image_tag picture_frame.image.url (:medium)), picture_frame
      %h2= link_to picture_frame.name, picture_frame
      %p.use
        Submitted by


.col-md-4.col-md-offset-4.center
  .form-inline
  .form-group
    = form_tag(picture_frames_path, :method => "get", id: "search-form") do
      = text_field_tag :search, params[:search], placeholder: "Search Picture_Frame", class: 'form-control'
      = submit_tag "Search", name: nil, class: 'btn btn-primary inline-button'
      %end

app/views/picture_frames/new.html.haml
.col-md-8.col-md-offset-2
	.row
		.panel.panel-default
			.panel-heading
				%h1 Add New Frame
			.panel-body
				= render 'form'

app/views/picture_frames/show.html.haml
#pin_show.row
	.col-md-8.col-md-offset-2
		.panel.panel-default
			.mymarginframe
				= image_tag @picture_frame.image.url (:original)
			.panel-body
				%h1= @picture_frame.name

			.panel-footer
				.row
					.col-md-6
						%p.user
							Submitted by

					.col-md-6
						.btn-group.pull-right
							= link_to "Edit", edit_picture_frame_path, class: "btn btn-default"
							= link_to "Delete", picture_frame_path, method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-default"