config/routes.rb
Rails.application.routes.draw do
  resources :picture_frames
  get 'picture_frames/portrait'

  get 'password_resets/new'

  get 'password_resets/edit'

  get 'sessions/new'

  get 'uses/new'

 resources :pins



  resources :pins do
  	resources :pins
  	member do
  		put "like",    to: "pins#upvote"
  	end
  end

  root "pins#index"
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  get 'signup'  => 'uses#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  resources :uses

  resources :pins
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :microposts,          only: [:create, :destroy]


end

app/views/layouts/_footer.html.haml
.col-md-4.col-md-offset-4.center
	.form-group
		= form_tag(pins_path, :method => "get", id: "search-form" class: 'form-inline') do
			= search_field_tag :search, params[:search], placeholder: "Search For Art", class: 'form-control'
			= submit_tag "Search", name: nil, class: 'btn btn-primary inline-button'

app/views/layouts/_header.html.haml
%header.navbar.navbar-fixed-top.navbar-inverse
  .container
    .navbar-brand= link_to "ArtRising.ie", root_path
    %nav
      %ul.nav.navbar-nav.navbar-right

        %li= link_to "Search", root_path
        %li= link_to "Home", root_path
        - if logged_in?
          %li= link_to "Artists", uses_path
          %li.dropdown
            %a.dropdown-toggle{"data-toggle" => "dropdown", href: "#"}
              My Profile
              %b.caret
            %ul.dropdown-menu
              %li= link_to "Profile", current_use
              %li= link_to "Settings", edit_use_path(current_use)
              %li= link_to "Add Art", new_pin_path
              %li.divider
              %li
                = link_to "Log out", logout_path, method: "delete"
        - else
          %li= link_to "Log in", login_path
       

app/views/layouts/application.html.haml
!!! 5
%html
%head
	%title ArtRising.ie
	= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
	= javascript_include_tag 'application', 'data-turbolinks-track' => true
	= csrf_meta_tags

%body
	= render :partial => "layouts/header"

.container.mymargin
	- flash.each do |name, msg|
		= content_tag :div, msg, class: "alert alert-info"
	= yield
.navbar.navbar-default.navbar-fixed-bottom
	.container
	.col-md-2.col-md-offset-2.pull-left
		.form-group
			= form_tag(pins_path, :class => "form-inline pull-left", :method => "get", id: "search-form") do
				= text_field_tag :search, params[:search], placeholder: "Search For Art", class: 'form-control'
				= submit_tag "Search", name: nil, class: 'btn btn-primary inline-button pull-left'